# Generated by Django 3.1.5 on 2021-06-22 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=100)),
                ('Last_Name', models.CharField(max_length=100)),
                ('Service', models.CharField(max_length=50)),
                ('Email', models.CharField(max_length=200)),
                ('Phone', models.CharField(max_length=20)),
                ('Message', models.TextField()),
                ('Date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
