# Generated by Django 3.1.5 on 2021-06-22 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='Company',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
