# Generated by Django 3.1.5 on 2021-06-25 03:42

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApp', '0003_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Body',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
