# Generated by Django 3.1.5 on 2021-06-25 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApp', '0004_auto_20210625_0342'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Meta_Tags',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
