# Generated by Django 3.1.5 on 2021-06-26 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApp', '0006_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Likes',
            field=models.IntegerField(null=True),
        ),
    ]
