# Generated by Django 3.1.5 on 2021-06-26 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApp', '0007_post_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Likes',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
