# Generated by Django 3.1.5 on 2021-06-27 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApp', '0008_auto_20210626_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Views',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
