# Generated by Django 3.1.5 on 2021-06-27 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApp', '0009_post_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Dis_Likes',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
