# Generated by Django 3.1.5 on 2021-06-28 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApp', '0013_auto_20210627_1622'),
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Link', models.CharField(max_length=200)),
                ('Customer', models.CharField(max_length=30)),
            ],
        ),
    ]
